module.exports = {
  apps: [
    {
      name: 'discord-bot',
      script: 'scripts/discord-bot-wrapper.sh',
      cwd: '/home/runner/strawberry',
      interpreter: '/bin/bash',
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 5000,
      exp_backoff_restart_delay: 1000,
      max_memory_restart: '512M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: '/home/runner/.pm2/logs/discord-bot-error.log',
      out_file: '/home/runner/.pm2/logs/discord-bot-out.log',
      merge_logs: true,
    },
    {
      name: 'discord-bridge',
      script: 'scripts/discord-bridge.sh',
      cwd: '/home/runner/strawberry',
      interpreter: '/bin/bash',
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 5000,
      exp_backoff_restart_delay: 1000,
      max_memory_restart: '256M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: '/home/runner/.pm2/logs/discord-bridge-error.log',
      out_file: '/home/runner/.pm2/logs/discord-bridge-out.log',
      merge_logs: true,
    },
    {
      name: 'result-watcher',
      script: 'scripts/result-watcher.sh',
      cwd: '/home/runner/strawberry',
      interpreter: '/bin/bash',
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 5000,
      exp_backoff_restart_delay: 1000,
      max_memory_restart: '256M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: '/home/runner/.pm2/logs/result-watcher-error.log',
      out_file: '/home/runner/.pm2/logs/result-watcher-out.log',
      merge_logs: true,
    },
  ],
};
