import { Octokit } from "@octokit/rest";
import { config } from "./config.js";
import { extractStrawberryMeta } from "./issue/parse.js";
import { resolveReviewers } from "./config/reviewers.js";

let _octokit: Octokit | null = null;

function octokit(): Octokit {
  if (!_octokit) {
    _octokit = new Octokit({ auth: config.github.token });
  }
  return _octokit;
}

function parseRepo(): { owner: string; repo: string } {
  const [owner, repo] = config.github.targetRepo.split("/");
  if (!owner || !repo) throw new Error(`Invalid TRIAGE_TARGET_REPO: ${config.github.targetRepo}`);
  return { owner, repo };
}

export interface CoderIssue {
  number: number;
  title: string;
  body: string;
}

/**
 * Fetch open issues labeled `myapps` AND `ready` but NOT `bot-in-progress`.
 */
export async function fetchReadyIssues(): Promise<CoderIssue[]> {
  const { owner, repo } = parseRepo();
  const { data } = await octokit().issues.listForRepo({
    owner,
    repo,
    state: "open",
    labels: "myapps,ready",
    per_page: 10,
  });

  // Filter out any that already have bot-in-progress or bot-pr-opened
  return data
    .filter((issue) => !issue.pull_request)
    .filter((issue) => {
      const labelNames = issue.labels.map((l) =>
        typeof l === "string" ? l : l.name ?? "",
      );
      return (
        !labelNames.includes("bot-in-progress") &&
        !labelNames.includes("bot-pr-opened")
      );
    })
    .map((issue) => ({
      number: issue.number,
      title: issue.title,
      body: issue.body ?? "",
    }));
}

export async function atomicLabelSwap(
  issueNumber: number,
  remove: string,
  add: string,
): Promise<void> {
  const { owner, repo } = parseRepo();
  await octokit().issues.removeLabel({
    owner,
    repo,
    issue_number: issueNumber,
    name: remove,
  });
  await octokit().issues.addLabels({
    owner,
    repo,
    issue_number: issueNumber,
    labels: [add],
  });
}

export async function createPr(
  branch: string,
  issueNumber: number,
  issueTitle: string,
  issueBody: string,
  issueLabels: string[],
): Promise<string> {
  const { owner, repo } = parseRepo();

  // Re-emit strawberry-meta block from the triggering issue (if present) so
  // downstream systems (GitHub Actions notify step) can read Discord metadata.
  const meta = extractStrawberryMeta(issueBody);
  const metaSuffix = meta
    ? "\n\n<!-- strawberry-meta\n" +
      Object.entries(meta)
        .map(([k, v]) => `${k}: ${v}`)
        .join("\n") +
      "\n-->"
    : "";

  const prBody =
    `Closes #${issueNumber}\n\n` +
    `This PR was opened automatically by the coder worker.\n\n` +
    `> **Review the diff and preview URL before merging.** The code was generated by Claude Code and must be reviewed by Duong.` +
    metaSuffix;

  const { data } = await octokit().pulls.create({
    owner,
    repo,
    head: branch,
    base: "main",
    title: `fix: ${issueTitle} (#${issueNumber})`,
    body: prBody,
    draft: false,
  });

  // Add bot-authored label
  await octokit().issues.addLabels({
    owner,
    repo,
    issue_number: data.number,
    labels: ["bot-authored"],
  });

  // Request reviewers — non-fatal on 422 (GitHub rejects self-review etc.)
  const reviewers = resolveReviewers(issueLabels);
  if (reviewers.length > 0) {
    try {
      await octokit().pulls.requestReviewers({
        owner,
        repo,
        pull_number: data.number,
        reviewers,
      });
    } catch (err: unknown) {
      const status = (err as { status?: number }).status;
      if (status === 422) {
        console.warn(
          `[coder-worker] requestReviewers 422 (self-review or unknown user) — continuing. Reviewers: ${reviewers.join(", ")}`,
        );
      } else {
        throw err;
      }
    }
  }

  return data.html_url;
}

export async function commentOnIssue(
  issueNumber: number,
  body: string,
): Promise<void> {
  const { owner, repo } = parseRepo();
  await octokit().issues.createComment({
    owner,
    repo,
    issue_number: issueNumber,
    body,
  });
}
