#!/usr/bin/env python3
"""Clean Claude Code session .jsonl files into a verbatim Markdown transcript.

Strips tool calls, tool results, system reminders, harness-injected context
blocks, and extended thinking. Only user prompts and assistant prose remain.

See plans/in-progress/2026-04-08-end-session-skill-phase-1.md Section 2 for the
full spec this script implements.

Python stdlib only. No pip installs.
"""

import argparse
import datetime
import hashlib
import json
import os
import pathlib
import re
import sys

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

CHAIN_GAP_SECONDS = 30 * 60  # 30 minutes — see Section 2.4

def _default_project_dir() -> pathlib.Path:
    """Return the Claude Code project dir for this repo on the current platform.

    On macOS and Linux, Claude Code stores session jsonl under
    ``~/.claude/projects/<slugified-repo-path>/``. The slug is produced by
    replacing every filesystem separator in the absolute repo path with a
    dash and prefixing a dash — e.g. ``/Users/duongntd99/Documents/Personal/strawberry``
    becomes ``-Users-duongntd99-Documents-Personal-strawberry``.

    On Windows, Claude Code uses the drive-letter + dash convention under
    ``%USERPROFILE%\\.claude\\projects\\``.

    The function resolves the repo root via ``git rev-parse --show-toplevel``
    and constructs the slug from that. Falls back to the current working
    directory if git is unavailable.
    """
    try:
        import subprocess
        repo_root = subprocess.check_output(
            ["git", "rev-parse", "--show-toplevel"],
            stderr=subprocess.DEVNULL,
        ).decode().strip()
        repo_path = pathlib.Path(repo_root)
    except (subprocess.CalledProcessError, FileNotFoundError, OSError):
        repo_path = pathlib.Path.cwd()

    home = pathlib.Path.home()
    projects_root = home / ".claude" / "projects"

    if sys.platform == "win32":
        # Windows: drive letter + dashes, e.g. C--Users-AD-Duong-strawberry
        drive = repo_path.drive.rstrip(":")  # "C:" -> "C"
        tail = str(repo_path)[len(repo_path.drive):].replace("\\", "-").replace("/", "-")
        slug = f"{drive}-{tail}" if tail.startswith("-") else f"{drive}--{tail}"
        return projects_root / slug

    # macOS / Linux: leading dash + dash-separated path
    slug = "-" + str(repo_path).lstrip("/").replace("/", "-")
    return projects_root / slug

# Secret denylist patterns (Section 2.9).
SECRET_PATTERNS = [
    ("age-pubkey", re.compile(r"age1[ac-hj-np-z02-9]{58}")),
    ("age-seckey", re.compile(r"AGE-SECRET-KEY-1[A-Z0-9]{58}")),
    ("sk-api-key", re.compile(r"sk-[A-Za-z0-9_-]{20,}")),
    ("github-pat", re.compile(r"ghp_[A-Za-z0-9]{30,}")),
    ("github-oauth", re.compile(r"gho_[A-Za-z0-9]{30,}")),
    ("slack-bot", re.compile(r"xoxb-[A-Za-z0-9-]{20,}")),
    ("slack-user", re.compile(r"xoxp-[A-Za-z0-9-]{20,}")),
    ("aws-akid", re.compile(r"AKIA[0-9A-Z]{16}")),
    (
        "private-key-pem",
        re.compile(r"-----BEGIN (RSA |EC |OPENSSH )?PRIVATE KEY-----"),
    ),
]

# Stripping regexes for user text (Section 2.7).
RE_SYSTEM_REMINDER = re.compile(
    r"<system-reminder>.*?</system-reminder>", re.DOTALL
)
RE_LOCAL_STDOUT = re.compile(
    r"<local-command-stdout>.*?</local-command-stdout>", re.DOTALL
)
RE_LOCAL_STDERR = re.compile(
    r"<local-command-stderr>.*?</local-command-stderr>", re.DOTALL
)
RE_COMMAND_NAME = re.compile(r"<command-name>.*?</command-name>", re.DOTALL)
RE_COMMAND_MSG = re.compile(r"<command-message>.*?</command-message>", re.DOTALL)
RE_COMMAND_ARGS = re.compile(r"<command-args>.*?</command-args>", re.DOTALL)
RE_LOCAL_CAVEAT = re.compile(
    r"Caveat: The messages below were generated by the user while running local commands.*?(?=\n\n|\Z)",
    re.DOTALL,
)
RE_TASK_NOTIFICATION = re.compile(
    r"<task-notification>.*?</task-notification>", re.DOTALL
)
# Also strip self-closing or unclosed `<local-command-caveat>` tags seen in
# real harness output (tag-form, no matching close tag).
RE_LOCAL_CAVEAT_TAG = re.compile(
    r"<local-command-caveat>(?:.*?</local-command-caveat>)?", re.DOTALL
)

# Denylist headers for harness-injected envelope detection (Section 2.7 step 6).
ENVELOPE_HEADERS = (
    "# claudeMd",
    "# currentDate",
    "# gitStatus",
    "# Memory Index",
)

RE_ENVELOPE_BLOCK = re.compile(
    r"^(?:<env>.*?</env>|<context>.*?</context>|# (?:claudeMd|currentDate|gitStatus|Memory Index)\b.*?)(?=\n# |\Z)",
    re.DOTALL | re.MULTILINE,
)

RE_THREE_NEWLINES = re.compile(r"\n{3,}")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def log_stderr(msg: str) -> None:
    print(msg, file=sys.stderr)


def die(code: int, msg: str) -> None:
    log_stderr(msg)
    sys.exit(code)


def content_hash(text: str) -> str:
    return hashlib.sha1(text.encode("utf-8", errors="replace")).hexdigest()


def normalize_whitespace(text: str) -> str:
    text = RE_THREE_NEWLINES.sub("\n\n", text)
    return text.strip()


def strip_user_text(text: str) -> str:
    """Apply Section 2.7 stripping rules in order."""
    if not text:
        return ""
    text = RE_SYSTEM_REMINDER.sub("", text)
    text = RE_LOCAL_STDOUT.sub("", text)
    text = RE_LOCAL_STDERR.sub("", text)
    text = RE_COMMAND_NAME.sub("", text)
    text = RE_COMMAND_MSG.sub("", text)
    text = RE_COMMAND_ARGS.sub("", text)
    text = RE_LOCAL_CAVEAT.sub("", text)
    text = RE_LOCAL_CAVEAT_TAG.sub("", text)
    text = RE_TASK_NOTIFICATION.sub("", text)

    # Envelope stripping (Section 2.7 step 6-7). If after removing envelope
    # blocks nothing is left, empty result — else keep surviving prose.
    stripped = RE_ENVELOPE_BLOCK.sub("", text)
    # If still contains an envelope header anywhere, strip from that header
    # to the next "# " header or end of string.
    for header in ENVELOPE_HEADERS:
        while header in stripped:
            idx = stripped.index(header)
            tail = stripped[idx + len(header):]
            next_hdr = tail.find("\n# ")
            if next_hdr == -1:
                stripped = stripped[:idx]
            else:
                stripped = stripped[:idx] + tail[next_hdr + 1:]
    text = stripped
    return normalize_whitespace(text)


def strip_assistant_text(text: str) -> str:
    """Section 2.8 — minimal stripping, just whitespace normalization."""
    if not text:
        return ""
    return normalize_whitespace(text)


def looks_like_skill_body(text: str) -> bool:
    """Detect harness-injected skill body markdown that slips past envelope
    stripping — long markdown docs starting with an H1 and several H2s."""
    if not text.startswith("# "):
        return False
    if len(text) < 500:
        return False
    head = text[:5000]
    h2_count = sum(1 for line in head.split("\n") if line.startswith("## "))
    return h2_count >= 3


def extract_user_content(message: dict) -> str:
    """Return cleaned user text (may be empty)."""
    content = message.get("content")
    if content is None:
        return ""
    if isinstance(content, str):
        if looks_like_skill_body(content):
            return ""
        return strip_user_text(content)
    if isinstance(content, list):
        parts = []
        for block in content:
            if not isinstance(block, dict):
                continue
            btype = block.get("type")
            if btype == "text":
                raw = block.get("text", "")
                if looks_like_skill_body(raw):
                    continue
                t = strip_user_text(raw)
                if t:
                    parts.append(t)
            # tool_result and other block types ignored
        return "\n\n".join(parts)
    return ""


def extract_assistant_content(message: dict) -> str:
    content = message.get("content")
    if content is None:
        return ""
    if isinstance(content, str):
        return strip_assistant_text(content)
    if isinstance(content, list):
        parts = []
        for block in content:
            if not isinstance(block, dict):
                continue
            if block.get("type") == "text":
                t = strip_assistant_text(block.get("text", ""))
                if t:
                    parts.append(t)
        return "\n\n".join(parts)
    return ""


def iso_timestamp(raw) -> str:
    if not raw:
        return "<unknown>"
    try:
        dt = datetime.datetime.fromisoformat(str(raw).replace("Z", "+00:00"))
        dt_utc = dt.astimezone(datetime.timezone.utc)
        return dt_utc.strftime("%Y-%m-%dT%H:%M:%SZ")
    except (ValueError, TypeError):
        return str(raw)


# ---------------------------------------------------------------------------
# Session-chain discovery
# ---------------------------------------------------------------------------


def list_project_jsonls(project_dir: pathlib.Path) -> list:
    entries = []
    try:
        for ent in os.scandir(project_dir):
            if ent.is_file() and ent.name.endswith(".jsonl"):
                entries.append((ent.stat().st_mtime, pathlib.Path(ent.path)))
    except FileNotFoundError:
        die(1, f"CLEANER: project dir not found: {project_dir}")
    entries.sort(key=lambda x: x[0], reverse=True)
    return entries  # list of (mtime, Path), newest first


def file_head_tail(path: pathlib.Path):
    """Return (first_hash, last_hash) of the file's user/assistant text content."""
    first = None
    last = None
    try:
        with path.open("r", encoding="utf-8", errors="replace") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    rec = json.loads(line)
                except json.JSONDecodeError:
                    continue
                if rec.get("isSidechain"):
                    continue
                msg = rec.get("message") or {}
                rtype = rec.get("type")
                if rtype == "user":
                    text = extract_user_content(msg)
                elif rtype == "assistant":
                    text = extract_assistant_content(msg)
                else:
                    continue
                if not text:
                    continue
                h = content_hash(text)
                if first is None:
                    first = h
                last = h
    except OSError:
        return None, None
    return first, last


def walk_chain(head: pathlib.Path, all_entries: list) -> list:
    """Given a head file, walk backwards by mtime adjacency to find chain.

    all_entries is the full (mtime, Path) list newest-first.
    Returns an ordered list of Paths, oldest first.
    """
    by_path = {p: m for m, p in all_entries}
    sorted_by_time = sorted(all_entries, key=lambda x: x[0])  # oldest first
    paths_time_order = [p for _, p in sorted_by_time]

    try:
        head_idx = paths_time_order.index(head)
    except ValueError:
        return [head]

    chain = [head]
    # Walk backwards.
    i = head_idx - 1
    while i >= 0:
        prev = paths_time_order[i]
        prev_mtime = by_path[prev]
        next_mtime = by_path[chain[0]]
        gap = next_mtime - prev_mtime
        if gap > CHAIN_GAP_SECONDS:
            break
        # Optional content-hash adjacency check: prev's last ~= chain[0]'s first.
        # Per Section 2.3: gap adjacency is primary, content hash is confirming.
        # We accept on gap alone; hash match strengthens, hash mismatch still OK
        # since UUIDs don't chain cleanly either (S23 finding).
        chain.insert(0, prev)
        i -= 1
    # Do NOT walk forward — head is the newest.
    return chain


def discover_chain(
    project_dir: pathlib.Path, session: str
) -> list:
    entries = list_project_jsonls(project_dir)
    if not entries:
        die(1, f"CLEANER: no session jsonl files in {project_dir}")

    if session == "auto":
        head = entries[0][1]
        return walk_chain(head, entries)

    # Explicit session: full UUID or 8-char prefix
    session_clean = session.lower()
    matches = []
    for _, p in entries:
        name = p.stem.lower()
        if name == session_clean or name.startswith(session_clean):
            matches.append(p)
    if not matches:
        die(1, f"CLEANER: session {session} not found in {project_dir}")
    # Pick the newest match as the head.
    head = max(matches, key=lambda p: by_mtime(p))
    return walk_chain(head, entries)


def by_mtime(p: pathlib.Path) -> float:
    try:
        return p.stat().st_mtime
    except OSError:
        return 0.0


# ---------------------------------------------------------------------------
# Record iteration
# ---------------------------------------------------------------------------


def iter_records(path: pathlib.Path):
    """Yield (record_dict, line_number) tuples. Skip malformed lines."""
    decode_errors = 0
    total_lines = 0
    try:
        with path.open("r", encoding="utf-8", errors="strict") as f:
            for lineno, raw in enumerate(f, start=1):
                total_lines += 1
                raw = raw.strip()
                if not raw:
                    continue
                try:
                    yield json.loads(raw), lineno
                except json.JSONDecodeError:
                    log_stderr(
                        f"CLEANER: skipped malformed line {lineno} in {path.name}"
                    )
                    continue
    except UnicodeDecodeError:
        # Retry with replacement tracking error rate
        with path.open("r", encoding="utf-8", errors="replace") as f:
            for lineno, raw in enumerate(f, start=1):
                total_lines += 1
                raw_stripped = raw.strip()
                if not raw_stripped:
                    continue
                try:
                    yield json.loads(raw_stripped), lineno
                except json.JSONDecodeError:
                    decode_errors += 1
                    if total_lines > 0 and decode_errors * 10 > total_lines:
                        die(
                            2,
                            f"CLEANER: >10% lines failed to decode in {path.name}",
                        )
                    log_stderr(
                        f"CLEANER: skipped malformed line {lineno} in {path.name}"
                    )


# ---------------------------------------------------------------------------
# Cleaning pipeline
# ---------------------------------------------------------------------------


def clean_chain(chain: list):
    """Yield (role, timestamp_iso, text) sections in order."""
    seen_uuids = set()
    seen_hashes_per_role = {"user": None, "assistant": None}

    for path in chain:
        for rec, lineno in iter_records(path):
            if not isinstance(rec, dict):
                continue
            if rec.get("isSidechain") is True:
                continue
            rtype = rec.get("type")
            if rtype not in ("user", "assistant"):
                continue
            msg = rec.get("message") or {}
            if rtype == "user":
                text = extract_user_content(msg)
            else:
                text = extract_assistant_content(msg)
            if not text:
                continue
            uid = rec.get("uuid")
            if uid and uid in seen_uuids:
                continue
            h = content_hash(text)
            # Dedup: skip if same role repeats same content hash back-to-back
            # at a chain boundary.
            if seen_hashes_per_role[rtype] == h:
                continue
            if uid:
                seen_uuids.add(uid)
            seen_hashes_per_role[rtype] = h
            # Reset the other role's last hash so alternation works.
            other = "assistant" if rtype == "user" else "user"
            seen_hashes_per_role[other] = None
            ts = iso_timestamp(rec.get("timestamp"))
            yield rtype, ts, text


# ---------------------------------------------------------------------------
# Secret scan
# ---------------------------------------------------------------------------


def scan_for_secrets(lines: list, out_path: pathlib.Path) -> None:
    for lineno, line in enumerate(lines, start=1):
        for name, pat in SECRET_PATTERNS:
            if pat.search(line):
                if name == "age-pubkey":
                    log_stderr(
                        f"CLEANER: WARNING — age public key found in output (not a secret, continuing). pattern={name}. line={lineno}"
                    )
                else:
                    die(
                        3,
                        f"CLEANER: secret pattern matched — refusing to write {out_path}. pattern={name}. line={lineno}",
                    )


# ---------------------------------------------------------------------------
# Output writer
# ---------------------------------------------------------------------------


def agent_label(agent: str) -> str:
    if not agent:
        return "Assistant"
    return agent[0].upper() + agent[1:]


def build_output(
    agent: str,
    chain: list,
    sections: list,
    chain_ambiguous: bool,
) -> tuple:
    """Return (lines_list, first_date_str, short_uuid, counts)."""
    first_user_ts = None
    user_count = 0
    assistant_count = 0
    for role, ts, _ in sections:
        if role == "user":
            user_count += 1
            if first_user_ts is None and ts != "<unknown>":
                first_user_ts = ts
        else:
            assistant_count += 1

    first_date = (first_user_ts or datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"))[:10]
    head_path = chain[-1] if chain else None
    short_uuid = head_path.stem[:8] if head_path else "unknown"

    now_iso = datetime.datetime.now(datetime.timezone.utc).strftime(
        "%Y-%m-%dT%H:%M:%SZ"
    )

    lines = []
    lines.append(f"# Session {short_uuid} — {first_date} — {agent}")
    lines.append("")
    lines.append(
        "> Cleaned transcript. Tool calls, tool results, system reminders, "
        "extended thinking, and harness-injected context blocks have been "
        "stripped. Only user prompts and assistant prose remain."
    )
    lines.append(">")
    lines.append("> Source files:")
    for p in chain:
        lines.append(f"> - {p}")
    lines.append(">")
    lines.append(f"> Cleaned at: {now_iso}")
    lines.append(
        f"> Message count: user {user_count}, assistant {assistant_count}"
    )
    chain_note = "ambiguous" if chain_ambiguous else "ok"
    lines.append(f"> Chain-walk: auto — {chain_note}")
    lines.append("")
    lines.append("---")
    lines.append("")

    if not sections:
        lines.append("> (no surviving user or assistant prose in this session)")
        lines.append("")
        return lines, first_date, short_uuid, (user_count, assistant_count)

    label = agent_label(agent)
    for role, ts, text in sections:
        speaker = "Duong" if role == "user" else label
        lines.append(f"## {speaker} — {ts}")
        lines.append("")
        lines.append(text)
        lines.append("")

    return lines, first_date, short_uuid, (user_count, assistant_count)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> int:
    parser = argparse.ArgumentParser(description="Clean Claude Code session .jsonl files.")
    parser.add_argument("--agent", required=True)
    parser.add_argument("--session", default="auto")
    parser.add_argument("--out", default=None)
    parser.add_argument("--project-dir", default=str(_default_project_dir()))
    args = parser.parse_args()

    agent = args.agent.strip().lower()
    if not re.match(r"^[a-z][a-z0-9-]*$", agent):
        die(1, f"CLEANER: invalid agent name: {agent}")

    project_dir = pathlib.Path(args.project_dir)
    chain = discover_chain(project_dir, args.session)
    if not chain:
        die(1, f"CLEANER: empty chain for session {args.session}")

    # Empty-file check
    for p in chain:
        if p.stat().st_size == 0:
            die(1, f"CLEANER: session {p.stem} is empty")

    sections = list(clean_chain(chain))

    out_lines, first_date, short_uuid, counts = build_output(
        agent=agent,
        chain=chain,
        sections=sections,
        chain_ambiguous=False,
    )

    if args.out:
        out_path = pathlib.Path(args.out)
    else:
        out_path = pathlib.Path(
            f"agents/{agent}/transcripts/{first_date}-{short_uuid}.md"
        )

    # Secret scan before writing.
    scan_for_secrets(out_lines, out_path)

    try:
        out_path.parent.mkdir(parents=True, exist_ok=True)
    except OSError as e:
        die(1, f"CLEANER: failed to create parent dir for {out_path}: {e}")

    try:
        with out_path.open("w", encoding="utf-8", newline="\n") as f:
            f.write("\n".join(out_lines))
            if not out_lines or not out_lines[-1] == "":
                f.write("\n")
    except OSError as e:
        die(1, f"CLEANER: failed to write {out_path}: {e}")

    log_stderr(
        f"CLEANER: wrote {out_path} — user={counts[0]} assistant={counts[1]} chain_len={len(chain)}"
    )
    print(str(out_path))
    return 0


if __name__ == "__main__":
    sys.exit(main())
