#!/bin/sh
# Auto-generated by scripts/sync-plugins.sh — do not edit manually
# Run scripts/sync-plugins.sh to regenerate from ~/.claude/settings.json

set -e

# Install each enabled Claude Code plugin.
# Skips gracefully if already installed (claude plugin install is idempotent).

claude plugin install "context7@claude-plugins-official" 2>/dev/null || true
claude plugin install "playwright@claude-plugins-official" 2>/dev/null || true
claude plugin install "firebase@claude-plugins-official" 2>/dev/null || true
claude plugin install "pr-review-toolkit@claude-plugins-official" 2>/dev/null || true
claude plugin install "frontend-design@claude-plugins-official" 2>/dev/null || true
claude plugin install "skill-creator@claude-plugins-official" 2>/dev/null || true
claude plugin install "firecrawl@claude-plugins-official" 2>/dev/null || true
claude plugin install "figma@claude-plugins-official" 2>/dev/null || true
claude plugin install "coderabbit@claude-plugins-official" 2>/dev/null || true
claude plugin install "superpowers@claude-plugins-official" 2>/dev/null || true
claude plugin install "goodmem@claude-plugins-official" 2>/dev/null || true
claude plugin install "remember@claude-plugins-official" 2>/dev/null || true

echo "install-plugins: done"
