#!/bin/sh
# sync-plugins.sh — reads ~/.claude/settings.json and regenerates scripts/install-plugins.sh
# POSIX-portable bash

SETTINGS="$HOME/.claude/settings.json"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
INSTALL_SCRIPT="$SCRIPT_DIR/install-plugins.sh"

# Exit silently if jq is missing
if ! command -v jq >/dev/null 2>&1; then
  exit 0
fi

# Exit silently if settings file is missing
if [ ! -f "$SETTINGS" ]; then
  exit 0
fi

# Extract enabled plugin keys (where value is true)
PLUGINS=$(jq -r '.enabledPlugins | to_entries[] | select(.value == true) | .key' "$SETTINGS" 2>/dev/null)

if [ -z "$PLUGINS" ]; then
  echo "sync-plugins: no enabled plugins found in $SETTINGS"
  exit 0
fi

# Build the install script
{
  printf '#!/bin/sh\n'
  printf '# Auto-generated by scripts/sync-plugins.sh — do not edit manually\n'
  printf '# Run scripts/sync-plugins.sh to regenerate from ~/.claude/settings.json\n'
  printf '\n'
  printf 'set -e\n'
  printf '\n'
  printf '# Install each enabled Claude Code plugin.\n'
  printf '# Skips gracefully if already installed (claude plugin install is idempotent).\n'
  printf '\n'
  for plugin in $PLUGINS; do
    printf 'claude plugin install "%s" 2>/dev/null || true\n' "$plugin"
  done
  printf '\n'
  printf 'echo "install-plugins: done"\n'
} > "$INSTALL_SCRIPT"

chmod +x "$INSTALL_SCRIPT"

PLUGIN_COUNT=$(printf '%s\n' "$PLUGINS" | wc -l | tr -d ' ')
echo "sync-plugins: regenerated $INSTALL_SCRIPT with $PLUGIN_COUNT plugin(s)"
