#!/bin/sh
# Auto-generated wrapper — delegates to check-no-hardcoded-slugs.sh
# Regenerated by scripts/install-hooks.sh. Do not edit directly.
REPO_ROOT="$(git rev-parse --show-toplevel)"
exec "$REPO_ROOT/scripts/hooks/check-no-hardcoded-slugs.sh" "$@"
